CREATE TABLE champion (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cost INT NOT NULL,
  traits VARCHAR(255) NOT NULL
);

CREATE TABLE trait (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  effect_description VARCHAR(255) NOT NULL
);

CREATE TABLE deck (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  tier VARCHAR(10) NOT NULL,
  description VARCHAR(500) NOT NULL,
  champion_ids VARCHAR(255) NOT NULL,
  hidden_recommend TINYINT(1) NOT NULL DEFAULT 0
);
