spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/tft_deck_lab
    username: tft
    password: tft1234
    driver-class-name: org.mariadb.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.tft.vo
server:
  port: 8080
