CREATE TABLE IF NOT EXISTS champion (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  cost INT NOT NULL,
  traits VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS trait (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  description VARCHAR(500)
);

CREATE TABLE IF NOT EXISTS deck (
  id BIGINT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  tier VARCHAR(10) NOT NULL,
  pick_rate DECIMAL(5,2) NOT NULL,
  win_rate DECIMAL(5,2) NOT NULL,
  hidden_potential BOOLEAN DEFAULT FALSE,
  summary VARCHAR(1000)
);
